name: api-gateway-workflow

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
    branches:
      - main
    paths:
      - 'api_gateway/**'
      - '.github/workflows/_service-ci-template.yaml'
      - '.github/workflows/api-gateway-workflow.yaml'
  push:
    branches:
      - main
    paths:
      - 'api_gateway/**'
      - '.github/workflows/_service-ci-template.yaml'
      - '.github/workflows/api-gateway-workflow.yaml'
  workflow_dispatch:

jobs:
  ci:
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/_service-ci-template.yaml
    with:
      service_name: api-gateway
      service_path: api_gateway
      image_name: victormungai/champs-api-gateway
    secrets: inherit
