name: ingestion-service-workflow

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
    branches:
      - main
    paths:
      - 'ingestion_service/**'
      - '.github/workflows/ingestion-service-workflow.yaml'
  push:
    branches:
      - main
    paths:
      - 'ingestion_service/**'
      - '.github/workflows/ingestion-service-workflow.yaml'
  workflow_dispatch:

jobs:
  ci:
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/_service-ci-template.yaml
    with:
      service_name: ingestion-service
      service_path: ingestion_service
      image_name: victormungai/champs-ingestion-service
    secrets: inherit
