name: product-service-workflow

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
    branches:
      - main
    paths:
      - 'product_service/**'
      - '.github/workflows/product-service-workflow.yaml'
  push:
    branches:
      - main
    paths:
      - 'product_service/**'
      - '.github/workflows/product-service-workflow.yaml'
  workflow_dispatch:

jobs:
  ci:
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/_service-ci-template.yaml
    with:
      service_name: product-service
      service_path: product_service
      image_name: victormungai/champs-product-service
    secrets: inherit
